config/routes.rb
Warmup::Application.routes.draw do
  

  get '/', to: 'animal#index',  as: :home
  post '/adopt', to: 'animal#adopt', as: :adopt
  match '/adopt', to: 'animal#adopt', via: :options

  post '/users/add', to: 'user#add'
  post '/users/login', to: 'user#login'
  post '/TESTAPI/resetFixture', to: 'user#reset_fixture'
  post '/TESTAPI/unitTests', to: 'user#unit_tests'

  resources :users

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  user       :string(255)
#  password   :string(255)
#  created_at :datetime
#  updated_at :datetime
#  count      :integer
#

class User < ActiveRecord::Base	

	# the success return code
    SUCCESS               =   1

    # cannot find the user/password pair in the database (for login only)
    ERR_BAD_CREDENTIALS   =  -1

    # trying to add a user that already exists (for add only)
    ERR_USER_EXISTS       =  -2

    # invalid user name (empty or longer than MAX_USERNAME_LENGTH) (for add)
    ERR_BAD_USERNAME      =  -3

    # invalid password name (longer than MAX_PASSWORD_LENGTH) (for add)
    ERR_BAD_PASSWORD      =  -4


    # maximum length of user name
    MAX_USERNAME_LENGTH = 128

    # maximum length of password
    MAX_PASSWORD_LENGTH = 128


	# validations
	validates :user, presence: true, uniqueness: true, length: { 
		maximum: MAX_USERNAME_LENGTH,
		too_long: "maximum of %{count} characters" 
	}
	validates :password, length: { 
		maximum: MAX_PASSWORD_LENGTH,
		too_long: "maximum of %{count} characters" 
	}

	# add new user with count = 1
	def self.add(user, password)
		current_user = new(user: user, password: password)
		if current_user.valid?
			current_user.count = 1
			current_user.save
			current_user.count
		else
			if user.empty? || user.length > 128
				ERR_BAD_USERNAME
			elsif exists?(user: user)
				ERR_USER_EXISTS
			elsif password.length > 128
				ERR_BAD_PASSWORD
			else
				false
			end
		end
	end

	# log in existing user and increase count by 1
	def self.login(user, password)
		current_user = find_by(user: user)
		if current_user.blank?
			ERR_BAD_CREDENTIALS
		elsif current_user.password != password
			ERR_BAD_CREDENTIALS
		else 
			current_user.count += 1
			current_user.save
			current_user.count
		end
	end

	def validate()
		
	end
end

app/controllers/animal_controller.rb
class AnimalController < ApplicationController

	skip_before_filter :verify_authenticity_token
	before_filter :cors_preflight_check
	after_filter :cors_set_access_control_headers

	def cors_set_access_control_headers
		# allow CORS (cross origin resource sharing)
		headers['Access-Control-Allow-Origin'] = '*'
		headers['Access-Control-Allow-Methods'] = 'POST, PUT, DELETE, GET, OPTIONS'
		headers['Access-Control-Max-Age'] = "1728000"
		headers['Access-Control-Request-Method'] = '*'
		headers['Access-Control-Allow-Headers'] = 'Origin, Content-type, Accept, Authorization, X-Requested-With, X-Prototype-Version, X-CSRF-Token'
	end

	def cors_preflight_check
	    if request.method == :options
			headers['Access-Control-Allow-Origin'] = '*'
			headers['Access-Control-Allow-Methods'] = 'POST, PUT, DELETE, GET, OPTIONS'
			headers['Access-Control-Allow-Headers'] = 'X-Requested-With, X-Prototype-Version, X-CSRF-Token'
			headers['Access-Control-Max-Age'] = '1728000'
			render :text => '', :content_type => 'text/plain'
	    end
	end

	def index
	
	end

	def adopt
		name = params[:name]
		animals = ["puppy", "kitten", "bunny"]
		pictures = { puppy: ["boo.jpg", "sleepycorgi.jpg", "pomeranianball.jpg"], 
			kitten: ["sleepykit.jpg", "upsidedownkit.jpg", "wolfkit.jpg"], 
			bunny: ["bunnyhatchling.jpg", "handfullofbun.jpg", "rollingbun.jpg"] 
		}
		domain = home_url
		path = "images/"
		pet = animals[rand(animals.length)]
		pet_picture = domain + path + pictures[pet.to_sym][rand(pictures[pet.to_sym].length)]
		pet_age = rand(11) + 1
		if params[:name]
			render json: {name: name, animal: pet, picture: pet_picture, age: pet_age}
		else 
			render json: {animal: pet, picture: pet_picture, age: pet_age}
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def index
  
  end

  def add
    user = params[:user]
    password = params[:password]
    num = User.add(user, password)
    if num < 0
      render json: {errCode: num}
    else 
      render json: {errCode: User::SUCCESS, count: num}
    end
  end

  def login
    user = params[:user]
    password = params[:password]
    num = User.login(user, password)
    if num < 0
      render json: {errCode: num}
    else
      render json: {errCode: User::SUCCESS, count: num}
    end
  end

  def reset_fixture
    User.destroy_all
    render json: {errCode: 1}
  end

  def unit_tests
    output = `rspec #{Rails.root}/spec/`
    example = /(\d+) example/.match(output)[1]
    failures = /(\d+) failures/.match(output)[1]
    render json: {nrFailed: failures.to_i, output: output, totalTests: example.to_i}
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/animal/index.html.erb
<div id="adopt-screen">
	<form>
		<label>Name your new buddy!</label>
		<input type="text" name="name" placeholder="pet name">
		<input class="adopt-button btn btn-primary" type="submit" value="Adopt a furball">
	</form>
</div>
<div id="pet-screen">
	<h1 class="name"></h1>
	<p class="info">He's a <span class="animal"></span>, who is <span class="age"></span> months old.</p>
	<p class="warning"></p>
	<img class="picture" src="">
</div>

<script type="text/javascript">
$(document).ready(function(){

	$('#pet-screen').hide();

	$('#adopt-screen .adopt-button').click(function(e){
		e.preventDefault();
		var name = $('#adopt-screen input[name=name]').val();
		console.log(name);
		$.ajax({
			type: 'POST',
		    url: 'http://adoptafurball.herokuapp.com/adopt',
		    data: JSON.stringify({name: name}),
		    contentType: 'application/json',
		    dataType: 'json',
		    success: function(data) {
		    	console.log(data);
		    	console.log(data.animal);
		    	$('#pet-screen .name').html(data.name);
		    	$('#pet-screen .animal').html(data.animal);
		    	$('#pet-screen .age').html(data.age);
		    	$('#pet-screen .picture').attr('src', data.picture);
		    	if (data['age'] < 6) {
		    		$('#pet-screen .warning').html('Please take extra good care of this wittle guy!');
		    	} else {
		    		$('#pet-screen .warning').html('This guy is old enough to ramble on his own.');
		    	}
		    	$('#pet-screen').show();
		    }
		});
	});

	/*
	$.ajax({
		type: 'POST',
	    url: 'http://adoptafurball.herokuapp.com/adopt',
	    data: JSON.stringify({name: "Cuddles"}),
	    contentType: 'application/json',
	    dataType: 'json',
	    success: function(data) {
	    	console.log(data);
	    }
	});

	$.ajax({
		type: 'POST',
	    url: 'http://carinaboowarmup.herokuapp.com/users/login',
	    data: JSON.stringify({user: "carinabooooo", password: "12345"}),
	    contentType: 'application/json',
	    dataType: 'json',
	    success: function(data) {
	    	console.log(data);
	    }
	});
	*/
});
</script>

app/views/home/index-callisto.html.erb
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

<script type="text/javascript">
$(document).ready(function(){
	$('#loginButton').click(function(e){
		e.preventDefault();
		var username = $('#username').val();
		var password = $('#password').val();
		console.log(username);
		$.ajax({
			type: 'POST',
			url: 'http://carinaboowarmup.herokuapp.com/users/login',
	        data: JSON.stringify({user: username, password: password}),
	        contentType: 'application/json',
	        dataType: 'jsonp',
	        success: function(data) {
	        	// $('#puppy').attr('src', 'http://placekitten.com.s3.amazonaws.com/homepage-samples/200/287.jpg');
	        	// $('#loginScreen').css('display','none');
	        	console.log(data);
	        	if (data['errCode'] == 1) {
	        		$('#count').html(data['count']);
	        		$('#name').html(username);
	        	} else if (data['errCode'] == -1) {
	        		// show a message for bad login

	        	}
	        }
		});
		$.ajax({
			type: 'POST',
			url: 'http://carinaboowarmup.herokuapp.com/users/login',
	        data: JSON.stringify({user: "carinaboo@berkeley.edu", password: "1234567890"}),
	        contentType: 'application/json',
	        dataType: 'jsonp',
	        success: function(data) {
	        	console.log(data);
	        }
		});
	});
	$('#registerButton').click(function(e){
		e.preventDefault();
		var username = $('#username').val();
		var password = $('#password').val();
		console.log(username);
		$.ajax({
			type: 'POST',
			url: '/users/add',
	        data: JSON.stringify({user: username, password: password}),
	        contentType: 'application/json',
	        dataType: 'jsonp',
	        success: function(data) {
	        	console.log(data);
	        }
		});
	});
});
</script>

<div id="message">
	Here will be where all the messages show :D
</div>
<div id="loginScreen">
	<img id="puppy" src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTu2JoVsk5WS6ZensA2mRk9YnoE2zhNHqKQxWUUF9qJVAGjrApb4KKbKg">
	<form>
		<input type="text" placeholder="username" id="username">
		<input type="password" placeholder="password" id="password">
		<input type="submit" value="Login" id="loginButton">
		<input type="submit" value="Register" id="registerButton">
	</form>
</div>
<div id="countScreen">
	Hello there <span id="name"></span>! You have logged in <span id="count"></span> times!
</div>

app/views/home/index-generosity.html.erb
	<title>Counter app</title>
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
	<style type="text/css">
		input[type=submit] {
			background-color: #ADD8E6;
			border-radius: 5px;
		}
		.message {
			background: yellow;
			padding: 10px;
			margin: 10px;
			width: 600px;
		}
	</style>
	<script type="text/javascript">


	$(document).ready(function(){
		$("#loginButton").click(function(e){
			e.preventDefault();
			var username = $("#username").val();
			var password = $("#password").val();
			console.log(username);
			$.ajax({
				type: 'POST',
		        url: '/users/login',
		        data: JSON.stringify({user: username, password: password}),
		        contentType: "application/json",
		        dataType: "json",
		        success: function(data){
		        	showCountPage(data);
		        }
			});
		});

		var showCountPage = function(data){
			console.log(data);
        	var errCode = data['errCode'];
        	var count = data['count'];
        	var username = $("#username").val();
        	if (errCode == 1) {
        		$("#name").html(username);
        		$("#count").html(count);
        	} else {
        		$("#countScreen").hide();
        		if (errCode == -1) {
        			$("#message").html("bad login!");
        		}
        	}
		};

		$("#registerButton").click(function(e){
			e.preventDefault();
			var username = $("#username").val();
			var password = $("#password").val();
			console.log(username);
			$.ajax({
				type: 'POST',
		        url: '/users/add',
		        data: JSON.stringify({user: username, password: password}),
		        contentType: "application/json",
		        dataType: "json",
		        success: function(data){
		        	console.log(data);
		        }
			});
		});
	});

	</script>
</head>
<body>
	<div id="messageError" class="message">
		
	</div>
	<div id="messageSuccess" class="message">
		
	</div>
	<div id="loginScreen">
		<form>
			<input type="text" id="username">
			<input type="password" id="password">
			<input type="submit" value="Login" id="loginButton">
			<input type="submit" value="Register" id="registerButton">
		</form>
	</div>
	<div id="countScreen">
		Hi <span id="name"></span>! You've logged in 
		<span id="count"></span> times.
	</div>
</body>

app/views/home/index-mockbox.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
</head>
<script type="text/javascript">
$(document).ready(function(){

	var messages = {
		'-1': 'Bad login credentials',
		'-2': 'User exists',
		'-3': 'Bad username',
		'-4': 'Bad password'
	};

	$('#loginButton').click(
		function(e) {
			e.preventDefault();
			var username = $('#usernameInput').val();
			var password = $('#passwordInput').val();

			$.ajax({
				type: 'POST',
		        url: '/users/login',
		        data: JSON.stringify({user: username, password: password}),
		        contentType: "application/json",
		        dataType: "json",
		        success: function(data) {
		        	console.log(data);
		        	$("#countScreen #name").html(username);
		        	$("#countScreen #count").html(data['count']);
		        	var errCode = (data['errCode']).toString();
		        	$("#message").html(messages[errCode]);

		        	$("#loginScreen").hide();
		        }
			});
		}
	);
	$('#registerButton').click(
		function(e) {
			e.preventDefault();
			var username = $('#usernameInput').val();
			var password = $('#passwordInput').val();
			console.log("sending"+username+password);
			$.ajax({
				type: 'POST',
		        url: '/users/add',
		        data: JSON.stringify({user: username, password: password}),
		        contentType: "application/json",
		        dataType: "json",
		        success: function(data) {
		        	console.log(data);
		        }
			});
		}
	);
});
</script>
<body>
	<div id="message"></div>
	<div id="loginScreen">
		<form>
			<input type="text" name="username" placeholder="username" id="usernameInput">
			<input type="password" name="password" placeholder="password" id="passwordInput">
			<input type="submit" value="Login" id="loginButton">
			<input type="submit" value="Register" id="registerButton">
		</form>
	</div>
	<div id="countScreen">
		Hi <span id="name"></span>! You've logged in <span id="count"></span> times!
	</div>
</body>
</html>

app/views/home/index.html.erb
<div id="home-page">
<center>
<div id="login-page" class="box">
  <div id="login-message" class="message"></div>
  <center>
    <form>
      <input id="login-username" type="text" name="username" placeholder="Username"><br>
      <input id="login-password" type="password" name="pwd" placeholder="Password"><br>
      <input id="login-button" class="btn btn-primary" type="submit" value="Login">
      <input id="add-user-button" class="btn btn-success" type="submit" value="Add User">
    </form>
  </center>
</div>

<div id="welcome-page" class="box">
  <div id="welcome-message" class="message"></div>
  <center>
    <form>
      <input type="submit" id="logout-button" value="Logout">
    </form>
  </center>
</div>
</center>
<div>

<script type="text/javascript">

$(document).ready(function() {
   show_login_page("Please sign in or create a new user")
 });

function show_login_page(message) {
  if(! message) message = "Please sign in or create a new user";
  $('#welcome-page').hide()
  $('#login-username').val("")
  $('#login-password').val("")
  $('#login-message').html(message)
  $('#login-page').show()
}

function show_welcome_page(user, count) {
   $('#login-page').hide();
   $('#welcome-page').show();
   $('#welcome-message').html("Welcome "+user+"<br>You have logged in "+count+" times.");
}

function handle_login_response(data, user) {
  if( data.errCode > 0 ) {
     c = data.count;
     show_welcome_page(user, c);
  } else {
     if( debug_flag ) {
        if( data.errCode != ERR_BAD_CREDENTIALS ) {
           alert( 'Illegal error code encounted for this state');
        }
     }
     show_login_page( get_message_for_errcode(data.errCode) );  
  }
}

function handle_add_user_response(data, user) {
  if( data.errCode > 0 ) {
     c = data.count;
     show_welcome_page(user, c);
  } else {
     if( debug_flag ) {
        if( data.errCode != ERR_BAD_USERNAME && data.errCode != ERR_USER_EXISTS ) {
           alert( 'Illegal error code encounted for this state');
        }
     }
     show_login_page( get_message_for_errcode(data.errCode) );  
  }
}

// POST to /users/login -- log in user and increase count
$('#login-button').click(function() {
   username = $('#login-username').val()
   password = $('#login-password').val()
   json_request("/users/login", { user: username, password: password }, function(data) { return handle_login_response(data, username); }, function(err) { alert('error occurred on request'); });

   return false;
});

// POST to /users/add -- create new user
$('#add-user-button').click(function() {
   username = $('#login-username').val()
   password = $('#login-password').val()
   json_request("/users/add", { user: username, password: password }, function(data) { return handle_add_user_response(data, username); }, function(err) {alert('error occurred on request'); });

   return false;
});

$('#logout-button').click(function() {
  show_login_page();

  return false;
});

/* do POST requests and handle responses */
function json_request(page, dict, success, failure) {
    $.ajax({
        type: 'POST',
        url: page,
        data: JSON.stringify(dict),
        contentType: "application/json",
        dataType: "json",
        success: success,
        error: failure
    });
}

debug_flag = false;

ERR_BAD_CREDENTIALS = (-1);
ERR_USER_EXISTS = (-2);
ERR_BAD_USERNAME = (-3);
ERR_BAD_PASSWORD  = (-4);


function get_message_for_errcode(code) {
    if( code == ERR_BAD_CREDENTIALS) {
        return ("Invalid username and/or password. Please try again.");
    } else if( code == ERR_BAD_USERNAME) {
        return ("The username cannot be empty or over 128 characters. Please try again.");
    } else if( code == ERR_USER_EXISTS) {
        return ("This user name already exists. Please try again.");
    } else if( code == ERR_BAD_PASSWORD) {
        return ("The password should be at most 128 characters long. Please try again");
    } else {
        if( debug_flag ) { 
            alert('Illegal error code encountered: ' + code); 
        }
        return ("Unknown error occured: " + code);
   }
}

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <title>Adopt A Furball</title>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/user/dashboard.html.erb
<center>
	<h1><%= @user %></h1>
	<div>You have logged in</div>
	<div><%= @count %>
	<div>times</div>
</center>


<%= link_to 'Log Out', home_path %>

app/views/user/index.html.erb
<h1>Listing users</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th>Login Count</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.user %></td>
        <td><%= user.password %></td>
        <td><%= user.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Home', users_all_path %>

app/views/user/jsontest.html.erb
<h1><%= @user %></h1>
<div><%= @password %></div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.user %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.user %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>